### ISSUE TITLE
Class 'Illuminate\Support\Facades\Http' not found

### ISSUE THREAD

**Issue by thiagok** [kutia-software-company/larafirebase#17]
Hi guys. I'm getting this error:

Symfony \ Component \ Debug \ Exception \ FatalThrowableError (E_ERROR)
Class 'Illuminate\Support\Facades\Http' not found

Laravel: 6.20.13

In my controller:

use Illuminate\Support\Facades\Http;
use Kutia\Larafirebase\Facades\Larafirebase;

Can someone help me please?

**Comment by gentritabazi01** [comment]
Why you use this in your Controller: `use Illuminate\Support\Facades\Http;` ?

Larafirebase uses this inside. No need to use in your Controller ?

**Comment by thiagok** [comment]
Hi @gentritabazi01, 

I've removed the line and got the same error:

Symfony \ Component \ Debug \ Exception \ FatalThrowableError (E_ERROR)
Class 'Illuminate\Support\Facades\Http' not found

**Comment by thiagok** [comment]
The error appear in this line:

(vendor/kutia-software-company/larafirebase/src/Services/Larafirebase.php)
        $response = Http::withHeaders

**Comment by gentritabazi01** [comment]
Just checked, laravel has no support for Http Client <= 6.
We need to update package.

**Comment by gentritabazi01** [comment]
Check: [Release 1.3.0](https://github.com/kutia-software-company/larafirebase/releases/tag/1.3.0)
