### ISSUE TITLE
authentication Key

### ISSUE THREAD

**Issue by Laozofficial** [kutia-software-company/larafirebase#20]
Very Good Package , Please i need to know what authentication token you're talking about in the _config/larafirebase.php_  , cause i have been all over my google console and i can only find API keys not authentication key #

**Comment by gentritabazi01** [comment]
Go to **Project Settings** on tab "**Cloud Messaging**", after that you will see "**Server key**" 🔑 .

![image](https://user-images.githubusercontent.com/35135482/113154633-7e511900-9238-11eb-80ce-7807e883ba70.png)

**Comment by Laozofficial** [comment]
Thank You so much

**Comment by davidwidjaya** [comment]
How to find Authentication Key **[UPDATED JUNE 2023]**

1.  **Open Firebase Console** in https://console.firebase.google.com/
2. **Open project settings**
3. In **Cloud Messaging Tab** you will see Cloud Messaging API (Legacy) is **Disabled** then you need to click on **yellow circle on picture below, there's an option says " Manage API in Google Cloud Console" then ENABLE it**

![Screenshot 2023-06-30 164226](https://github.com/kutia-software-company/larafirebase/assets/72877723/5e9ce31e-5d0a-443f-90f6-d2e2f1bd297f)

**Comment by ZakDaMack** [comment]
Is there any plan to migrate to Firebase's new Firebase Cloud Messaging API (V1), as it looks like google will be removing this functionaily completely by 20/6/2024

https://firebase.google.com/docs/cloud-messaging/migrate-v1
