### ISSUE TITLE
what is difference sendNotification and sendMassage ?

### ISSUE THREAD

**Issue by vahidalvandi** [kutia-software-company/larafirebase#23]
hello . i use this package but same time not work and same time work , for example when sent sendNotification to mobile same time work ...

**Comment by gentritabazi01** [comment]
`sendNotification` forms `payload` it in this way:

```json
{
    "registration_ids": "",
    "notification": {
        "title": "",
        "body": "",
        "image": "",
        "click_action": ""
    },
    "priority": ""
}
```

`sendMessage` forms `payload` it in this way:

```json
{
    "registration_ids": "",
    "data": {
        "title": "",
        "body": "",
        "image": "",
        "click_action": ""
    },
    "priority": ""
}
```

You can read about the difference in firebase.

About "same time not work and same time work" you need to make sure you have written the code well on mobile.
