### ISSUE TITLE
Send to a topic?

### ISSUE THREAD

**Issue by beard7** [kutia-software-company/larafirebase#24]
Is there any method of sending to a topic? If so, I'll be able to swap out my current FCM package, which was mysteriously stopped working.

Thanks

**Comment by gentritabazi01** [comment]
Support for topic will be in next release.

Thanks.

**Comment by yogithesymbian** [comment]
any update ? i looking for sent by topic

**Comment by kustanbruno** [comment]
I'm interested too.

**Comment by ankurk91** [comment]
One can opt-in for this package 

https://github.com/ankurk91/fcm-notification-channel

It has topic support

**Comment by gentritabazi01** [comment]
PR created, we just need refactor.

**Comment by yogithesymbian** [comment]
i have alternative just handle on backend side to subscribe by topic , so in frontend we only get token and sent the registrationtoken to your backend side where have access **firebase sdk**.

**Comment by dz0nika** [comment]
Any updates on this feature?

**Comment by gentritabazi01** [comment]
> Any updates on this feature?


Currently, not.

**Comment by gentritabazi** [comment]
Check out the latest package by the author at https://github.com/gg-innovative/larafirebase.

This new package, which will be actively maintained, offers support for **FCM HTTP V1 API** and **FCM Topics**.
