### ISSUE TITLE
do fill data in js worker in require ?

### ISSUE THREAD

**Issue by vahidalvandi** [kutia-software-company/larafirebase#25]
```
    firebase.initializeApp({
        'messagingSenderId': '{MESSAGING_SENDER_ID}',
        'apiKey': '{API_KEY}',	
        'projectId': '{PROJECT_ID}',	
        'appId': '{APP_ID}'
    });
```

**Comment by gentritabazi01** [comment]
Question is not clear!

**Comment by gentritabazi01** [comment]
This is just example if you want to use in frontend.

**Comment by vahidalvandi** [comment]
please help me . i use js in frontend for enable allow notification  by user , and se api key in config . 
do i can remove javascript-client in my project ??

**Comment by gentritabazi01** [comment]
javascript-client is just example for frontend, you don't need to use in backend.
