### ISSUE TITLE
correct tooken format

### ISSUE THREAD

**Issue by vahidalvandi** [kutia-software-company/larafirebase#35]
hi , do this coorect format ?

['{TOKEN_1}', '{TOKEN_2}']

["{sdfsd}","{fhsd}"]

this is one real token and seny many like this to 
**'{cXv99TFMHPwyMxy84UnXlf:APA91bErGR73C-69-SCsWugEiHXwSZHobu2V8UVIG_a_QnmJPbsAJFwZ5_XtlSiL4DFINvkL-Qlybh-6XDMCXMOIkUIPrg8Cd0_8KDbSUmymx1ZJWvYDxrPdg7zqippInSlyf62HCehT}'**

**Comment by gentritabazi01** [comment]
```php
$tokens = ['cXv99TFM', 'vgubhinjnh']
```

**Comment by vahidalvandi** [comment]
@gentritabazi01 thanks please correct docs ['{TOKEN_1}', '{TOKEN_2}'] to **['TOKEN_1', 'TOKEN_2']**
