### ISSUE TITLE
Send a badge property

### ISSUE THREAD

**Issue by Artyomushko** [kutia-software-company/larafirebase#49]
Send a `badge` property to set a number for unread notifications in iOS.
This property should be sent in `notification` array but not in `data` array.

There is a PR already for that but it is closed. I think it should be reopened and then accepted.
https://github.com/kutia-software-company/larafirebase/pull/41

Right now it works if we use `fromArray` method instead of `withTitle`, `withBody` and `withAdditionalData` methods. This is not very convenient.

**Comment by gentritabazi01** [comment]
> Right now it works if we use fromArray method instead of withTitle, withBody and withAdditionalData methods. This is not very convenient.

This is the right way to use for now.

> Send a badge property to set a number for unread notifications in iOS.

If we plan to include all properties that will be a huge list. Also like you are saying `badge` is only for iOS.
