### ISSUE TITLE
Got undefined

### ISSUE THREAD

**Issue by jhoanborges** [kutia-software-company/larafirebase#53]
TEstes using you code, but sometimes it shows undefined and everything seems normal.

`        $deviceTokens = User::whereNotNull('fcm_token')->pluck('fcm_token')->toArray();

        return Larafirebase::withTitle('Test Title')
        ->withBody('Test body')
        ->withImage('https://firebase.google.com/images/social.png')
        ->withIcon('https://seeklogo.com/images/F/firebase-logo-402F407EE0-seeklogo.com.png')
        ->withSound('default')
        ->withClickAction('https://www.google.com')
        ->withPriority('high')
        ->withAdditionalData([
            'color' => '#rrggbb',
            'badge' => 0,
        ])
        ->sendNotification($deviceTokens);`

![Screenshot_20220902_155030](https://user-images.githubusercontent.com/32471957/188233573-809c6e57-e383-4ae5-bad6-2924f5d2a7d6.png)

**Comment by gentritabazi** [comment]
Please provide more details otherwise this issue should be closed.
