### ISSUE TITLE
Click_Action Not Working ?

### ISSUE THREAD

**Issue by benahmetcelik** [kutia-software-company/larafirebase#54]
Hi, ı working to send notification with this package but click action not working.
Image,title,body OK but url not working.

This my code :
`
 Larafirebase::withTitle('Example Title')
                ->withBody('Example Body')
                ->withClickAction('https://mysite.com/my-post-url')
                ->withImage('https://firebase.google.com/images/social.png')
                ->withIcon('https://firebase.google.com/images/social.png')
                ->withPriority('high')
                ->sendNotification($token);
`

**Comment by gentritabazi01** [comment]
https://github.com/kutia-software-company/larafirebase/discussions/29

**Comment by gentritabazi01** [comment]
It should. Make sure the URL is HTTPS. For more, please refer to firebase documentation.

**Comment by benahmetcelik** [comment]
Thank you so much. I will continue to review the documentation. Thanks for your time. Happy coding :)
