### ISSUE TITLE
Device Tokens

### ISSUE THREAD

**Issue by RichieMcMullen** [kutia-software-company/larafirebase#6]
Great package but how do we go about getting user device tokens in order to send messages  / notifications?

**Comment by gentritabazi01** [comment]
Check example how to receive messages or push notifications in a [JavaScript client](https://github.com/kutia-software-company/larafirebase/tree/master/javascript-client), also how to get **Device Token**.

**Comment by RichieMcMullen** [comment]
Thank you @gentritabazi01
