### ISSUE TITLE
Able to receive success response but app don't receive any notification

### ISSUE THREAD

**Issue by rexyou0831** [kutia-software-company/larafirebase#60]
Hi there,

I was try to use this package in my laravel project (ver 9.48.0), the response is successful which show as below
`{"multicast_id":7727002467209272154,"success":1,"failure":0,"canonical_ids":0,"results":[{"message_id":"0:1680837697229703%1eb521c9f9fd7ecd"}]}`

But my phone didn't received any notification. In my project, I used only this lines
`    public function notification_v1(Request $request){
        $token_array = [];
        $token_array[] = $request->token;
        return Larafirebase::withTitle($request->title)
                    ->withBody($request->message)
                    ->sendMessage($token_array);
   }`
   
 So I'm try using CURL and it worked to receive notication. So may I know did I missed out any part?

**Comment by gentritabazi** [comment]
Use `sendNotification` instead of `sendMessage`.
