### ISSUE TITLE
"message": "Driver [firebase] not supported.",

### ISSUE THREAD

**Issue by zooni7054** [kutia-software-company/larafirebase#61]
I am using firebase in notifications. But giving errors. Any help?

/**
     * Get the notification's delivery channels.
     *
     * @param  mixed $notifiable
     * @return array
     */
    public function via($notifiable)
    {
        $array = ['database', 'broadcast', 'firebase'];
        return $array;
    }
    
    public function toFirebase($notifiable)
    {
        $tokens = FcmToken::where(['login_type' => 1, 'user_id' => $notifiable->id, 'user_type' => $notifiable->getTable()])->pluck('token')->toArray();

        if (count($tokens) > 0) {
            return $response = Larafirebase::fromRaw([
                'registration_ids' => $tokens,
                'priority' => 'high',
                'data' => [
                    'badge' => 0,
                    'color' => '#rrggbb',
                    'notification_type' => $this->notification_type,
                    'title' => $this->notification_type,
                    'body' => $this->message,
                    // 'icon' => 'https://seeklogo.com/images/F/firebase-logo-402F407EE0-seeklogo.com.png',
                    // 'image' => 'https://firebase.google.com/images/social.png',
                ],
                // 'notification' => [
                //     'title' => $this->notification_type,
                //     'body' => $this->message,
                //     // 'icon' => 'https://seeklogo.com/images/F/firebase-logo-402F407EE0-seeklogo.com.png',
                //     // 'image' => 'https://firebase.google.com/images/social.png',
                // ],
                'android' => [
                    'priority' => 'high',
                    'ttl' => 3600,
                    'content_available' => true
                ],
                'apns' => [
                    'payload' => [
                        'aps' => [
                            'priority' => 'high',
                            'sound' => 'default',
                            'badge' => 1,
                            'content_available' => true
                        ],
                    ]
                ]
            ])->send();
        }

    }

**Comment by gentritabazi** [comment]
Can you try to clear the config cache `php artisan config:clear` ?

**Comment by zooni7054** [comment]
Yes, I did cache:clear and config:clear both.

**Comment by gentritabazi** [comment]
This has nothing to do with the package, you messed up some configurations when you installed the package and it resulted in this error.

Try reinstalling the package again!
